### ISSUE TITLE
Hi Raphael..

### ISSUE THREAD

**Issue by saifulapm** [glepnir/nvim#31]
Hello Raphael, I am fan of your works. That's why I was following your profile for long time. I see you was inactive in GitHub for a long time.  Everything good ? Everything was okay ? Glad to see you again.

**Comment by glepnir** [comment]
I'm sorry to have been away for so long. In the past year, I had to undergo two surgeries due to my health problems. I was discharged last week. Since I haven't written code and followed nevim's progress for too long, I need some time to look at the new features of neovim and these issues in my projects. thanks.

**Comment by saifulapm** [comment]
> I'm sorry to have been away for so long. In the past year, I had to undergo two surgeries due to my health problems. I was discharged last week. Since I haven't written code and followed nevim's progress for too long, I need some time to look at the new features of neovim and these issues in my projects. thanks.

Glad to hear that. Hope you will be back in neovim world soon. Thanks
